baseURL = 'https://shadybraden.com/'
languageCode = 'en-us'
title = 'shadybraden'
theme = 'PaperMod'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 10
[[menu.main]]
    identifier = "Jetlag"
    name = "Jetlag(ish)"
    url = "/jetlag/"
    weight = 20

[params.homeInfoParams]
    Title = "Welcome to my open source website"
    Content = "Built with Hugo and running on Cloudflare"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/shadybraden"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bradenholm"
[[params.socialIcons]]
    name = "pixelfed"
    url = "https://pixelfed.social/shadybraden"
[[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/shadybraden.com"

[params]
    defaultTheme = 'dark'
    favicon = "/favicon.ico"
    mainSections = ["articles"]

[outputs]
    articles = ['html', 'rss']
    wire = ['html', 'rss']
