baseURL = 'https://shadybraden.com/'
languageCode = 'en-us'
title = 'shadybraden'
theme = 'PaperMod'
paginate = 50

[[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 2
[[menu.main]]
    identifier = "Aircraft"
    name = "Aircraft"
    url = "/Aircraft/"
    weight = 3
[[menu.main]]
    identifier = "Jetlag"
    name = "Jetlag(ish)"
    url = "/jetlag/"
    weight = 4
[[menu.main]]
    identifier = "Search"
    name = "Search"
    url = "/Search/"
    weight = 5

[params.homeInfoParams]
    Title = "Welcome to my open source website"
    Content = "Built with Hugo and running on Cloudflare"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/shadybraden"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bradenholm"
[[params.socialIcons]]
    name = "pixelfed"
    url = "https://pixelfed.social/shadybraden"
[[params.socialIcons]]
    name = "bluesky"
    url = "https://bsky.app/profile/shadybraden.com"

[params]
    defaultTheme = 'dark'
    favicon = "/favicon.ico"
    mainSections = ["articles"]
    ShowCodeCopyButtons = 'true'
    ShowBreadCrumbs = 'true'
    ShowPostNavLinks = 'true'
    ShowReadingTime= 'true'

[outputs]
    articles = ['html', 'rss']
    aircraft = ['html', 'rss']
    home = [ "HTML", "RSS", "JSON" ]

[params.assets]
    favicon = "/assets/favicon.ico"
    favicon16x16 = "/assets/favicon-16x16.png"
    favicon32x32 = "/assets/favicon-32x32.png"
    apple_touch_icon = "/assets/apple-touch-icon.png"
