baseURL = 'https://shadybraden.com/'
languageCode = 'en-us'
title = 'shadybraden'
theme = 'PaperMod'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = 10
#[[menu.main]]
#    identifier = "Jetlag"
#    name = "Jetlag"
#    url = "/jetlag/"
#    weight = 20

[params.homeInfoParams]
    Title = "Welcome to my open source website"
    Content = "Built with Hugo wooooo"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/shadybraden"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bradenholm"

[params]
    defaultTheme = 'dark'
