baseURL = 'https://shadybraden.com/'
languageCode = 'en-us'
title = 'shadybraden'
theme = 'PaperMod'

[[menu.main]]
identifier = "articles"
name = "Article"
url = "/article/"
weight = 10
[[menu.main]]
identifier = "jetlag"
name = "jetlag"
url = "/jetlag/"
weight = 20

[params.homeInfoParams]
Title = "Welcome to my open source blog"
Content = "Built with Hugo wooooo"

[[params.socialIcons]]
name = "github"
url = "https://github.com/shadybraden"
[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com"

[params]
defaultTheme = 'dark'
